### PR TITLE
Enforce `===` and `!==`

### PR DESCRIPTION
**Pull request by hudochenkov**
Suggested in https://github.com/stylelint/stylelint/pull/2262#discussion_r96867449

http://eslint.org/docs/rules/eqeqeq

### CODE REVIEW

**Comment by davidtheclark** [comment]
Let's use the "smart" option if we add this rule: http://eslint.org/docs/rules/eqeqeq#smart

**Comment by hudochenkov** [comment]
What are reasons to loose this rule strictness with “smart” option? Isn't it easier always stick to `===` rather than find excuses to use `==` sometimes. I'm not arguing, it's just for my education :)

**Comment by evilebottnawi** [comment]
@hudochenkov I support it

**Comment by evilebottnawi** [comment]
If we have code as example
```js
// Very difficult logic
if ($someVariable == null) {
  // Some logic
}
```
For instance someone decided to rewrite code (refactoring, more logic, features and etc), he could face a lack of understanding variable should be equal null or undefined or a logical error that allowed the programmer accidentally.

**Comment by davidtheclark** [comment]
>  find excuses to use == sometimes

It's just a matter of understanding the language, not a matter of finding excuses. 

I guess you two right, though, that we should include the rule to catch devs who don't understand the language very well.

**Comment by jeddy3** [comment]
Sounds like you three are in agreement.

**Pull request merged**
