### PR TITLE
Prepare 19.0.0

### PR DESCRIPTION
**Pull request by ybiquitous**
> Which issue, if any, is this issue related to?

None.

> Is there anything in the PR that needs further explanation?

Diff: https://github.com/stylelint/eslint-config-stylelint/compare/18.0.0...main

### CODE REVIEW

**Comment by ybiquitous** [comment]
### Test on stylelint/stylelint

1. Install

```console
$ npm i -D 'github:stylelint/eslint-config-stylelint#prepare-19.0.0'
```

2. Check `package.json`

```console
$ git diff package.json
diff --git a/package.json b/package.json
index 387aef7f..20b689ad 100644
--- a/package.json
+++ b/package.json
@@ -179,7 +179,7 @@
     "common-tags": "^1.8.2",
     "deepmerge": "^4.3.1",
     "eslint": "^8.42.0",
-    "eslint-config-stylelint": "^18.0.0",
+    "eslint-config-stylelint": "github:stylelint/eslint-config-stylelint#prepare-19.0.0",
     "eslint-plugin-jest": "^27.2.1",
     "husky": "^8.0.3",
     "jest": "^29.5.0",
```

3. Run ESLint

```console
$ npm run lint:js

> stylelint@15.7.0 lint:js
> eslint . --cache --max-warnings=0 --ext .js,.mjs


/Users/masafumi.koba/git/stylelint/stylelint/lib/__tests__/fixtures/config-require-unknown.js
  3:26  error  "./someUnknownFile.js" is not found                          n/no-missing-require
  3:51  error  Definition for rule 'node/no-missing-require' was not found  node/no-missing-require

/Users/masafumi.koba/git/stylelint/stylelint/lib/cli.js
  387:3  error  Don't use process.exit(); throw an error instead  n/no-process-exit

/Users/masafumi.koba/git/stylelint/stylelint/lib/testUtils/safeChdir.js
  2:43  error  "@jest/globals" is extraneous                                   n/no-extraneous-require
  2:61  error  Definition for rule 'node/no-extraneous-require' was not found  node/no-extraneous-require

/Users/masafumi.koba/git/stylelint/stylelint/scripts/remark-changelog-to-github-release.mjs
  1:1   error  Definition for rule 'node/no-extraneous-import' was not found  node/no-extraneous-import
  2:23  error  "unist-util-visit" is extraneous                               n/no-extraneous-import

✖ 7 problems (7 errors, 0 warnings)
```

We need to rewrite `node/` to `n/`, but there should be no other problems.

**Review by mattxwang — APPROVED** [review]
LGTM! And thanks for making the changelog style more consistent.

**Review by mattxwang — APPROVED** [review]
So sorry - missed the notification here earlier! Still LGTM, and good callout on the migration note.

**Comment by ybiquitous** [comment]
@mattxwang Thanks for the re-review! I'll release `19.0.0` today.

**Comment by ybiquitous** [comment]
Oops. `npm run version` (`np`) raises the following error.

```
Error: Please include a `engines.node` field in your package.json
```

It seems necessary to add `engines.node` 😓

**Comment by mattxwang** [comment]
Thanks for opening the PR!

I'm curious, was this a recent development? I imagine we hadn't had this issue in the past when releasing versions of the config.

**Comment by ybiquitous** [comment]
Good point. `np@8.0.1` seems to add this change via https://github.com/sindresorhus/np/commit/beb7db1ba7d2ec4985d3d0211a7d4a37c72fc80f 🤔

**Pull request merged**
