### PR TITLE
chore(package): update eslint to version 3.0.0

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by ntwb** [comment]
@jeddy3 Should a new release of `eslint-config-stylelint` occur, `2.1.0`, or `3.0.0` before adding the ESLint 3.0.0 change to the other stylelint repos?

**Comment by TrySound** [comment]
@ntwb AFAIK eslint3 doesn't support node0.12.
http://eslint.org/blog/2016/07/eslint-v3.0.0-released#breaking-changes

**Comment by ntwb** [comment]
@TrySound Yes, that is correct, I'm also not against following the same methodology ESLint have outlined and drop support for NodeJS 0.12.x now as 0.12.x is end-of-life soon anyway:
> _"ESLint v3.0.0 now requires Node.js 4 or higher. Going forward, our plan is always to support the LTS version of Node.js and periodically end-of-life support for older Node.js versions. As both Node.js v0.10 and v0.12 will be out of maintenance mode at the end of 2016, we hope that this change won’t affect too many users."_

Currently stylelint is tested with Travis CI with 0.12.x, 4.x, and 6.x, when 0.10.x was dropped it was only dropped in testing and not explicitly declared in `package.json`, I think switching all stylelint repos to require a minimum of NodeJS 4.x.x LTS (4.2.1) would be the way to go.

When can do this as a breaking change as part of stylelint v7?

cc @stylelint/core

**Comment by jeddy3** [comment]
> We can do this as a breaking change as part of stylelint v7?

Anything that decreases our maintenance burden has my vote. `v7` seems like a good a time as any to do this.

**Comment by jeddy3** [comment]
> Should a new release of eslint-config-stylelint occur, 2.1.0, or 3.0.0 before adding the ESLint 3.0.0 change to the other stylelint repos?

I think it should be `3.0.0` right as removing node 4.0 support is a breaking change?

**Comment by ntwb** [comment]
Yes, `3.0.0` removing NodeJS `0.12.x` support would be a `major` change similar to ESLint bumping `major` themselves here.

I'll create a pull request declaring NodeJS 4.x.x LTS support now

**Comment by ntwb** [comment]
> I'll create a pull request declaring NodeJS 4.x.x LTS support now

Done in https://github.com/stylelint/eslint-config-stylelint/pull/7

**Pull request merged**
