### PR TITLE
Prepare release for v12.2.0

### PR DESCRIPTION
**Pull request by ybiquitous**
Related PRs:
- #99

Diff: https://github.com/stylelint/eslint-config-stylelint/compare/12.1.0...a3b437c2ce94932d15f99fd84c8b18530bc2dcbb

> Which issue, if any, is this issue related to?

None.

> Is there anything in the PR that needs further explanation?

No, it's self-explanatory.

### CODE REVIEW

**Comment by ybiquitous** [comment]
Wait for #101

**Review by jeddy3 — APPROVED** [review]

**Comment by hudochenkov** [comment]
I think it should have been major version, because we add rule, and it will break builds in a semver range.

**Comment by ybiquitous** [comment]
Oh, [v12.1.0](https://github.com/stylelint/eslint-config-stylelint/releases/tag/12.1.0) added `eslint-plugin-jest` recommended rules via bumping. (see #92)

But, I will follow our community decision or policy.
(FYI. https://github.com/eslint/eslint/tree/v7.11.0#semantic-versioning-policy)

**Comment by ybiquitous** [comment]
Sorry, I understood that v12.1.0 was irregular historically of this package.
I've opened PR #102 newly.

**Pull request merged**
